package package1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import static package1.FirstForm.jButton1;
import javax.swing.JTextField;
import javax.swing.text.DateFormatter;
import package1.FirstForm;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Label;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.View.Y_AXIS;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import static package1.Clear.ClearFFrame;
import static package1.Second.FindPatients;
import static package1.Second.clean;
import static package1.Second.getAdv;
import static package1.Second.getObj;
import static package1.Second.getSchedule;
import static package1.Second.rr;
import static package1.Second.wr;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniil
 */
public class SecondForm extends javax.swing.JFrame
{
public static String title;
public static SecondForm sc = new SecondForm();
public static  DefaultTableModel model1 ;
public static  DefaultTableModel model2 ;
public static  DefaultTableModel model3 ;
public static String patient = "";
    public SecondForm()
    {
    try
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(new Color(0,153,153));
        jInternalFrame2.setVisible(false);
        jInternalFrame3.setVisible(false);
        jInternalFrame3.setClosable(true);
        jInternalFrame5.setVisible(false);
        jInternalFrame4.setVisible(false);
        jInternalFrame7.setVisible(false);
        jTable1.setVisible(false);
        model1 = new DefaultTableModel();
        model1.addColumn("Код скидки");
        model1.addColumn("Содержание скидки");
        model1.addColumn("Размер скидки,%");
        Second.getDiscounts();
        jTable1.setModel(model1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable2.setVisible(false);
        model2 = new DefaultTableModel();
        model2.addColumn("Код услуги");
        model2.addColumn("Название услуги");
        model2.addColumn("Цена");
        getObj();
        jTable2.setModel(model2);
         jTable2.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        jInternalFrame4.setLocation(960, 540);
        jInternalFrame2.setLocation(960, 540);
        jInternalFrame5.setLocation(960, 540);
        jInternalFrame6.setLocation(960, 540);
        jInternalFrame7.setLocation(960, 540);
        jScrollPane1.setEnabled(false);
        jScrollPane2.setEnabled(false);
        jScrollPane3.setEnabled(false);
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable2.setEnabled(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable3.setEnabled(false);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jInternalFrame6.setVisible(false);
        ArrayList<String> item = new ArrayList<String>();
        ArrayList<String> act = new ArrayList<String>();
        Second.getItem(item);
         Object[] arr = item.toArray();
         Object[] act1 = act.toArray();
         for(int i=0;i<item.size();i++){
            jComboBox3.addItem(arr[i].toString());
        }
         
        
        
            
        
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel7 = new javax.swing.JLabel();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        button1 = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        textField1 = new javax.swing.JTextField();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 101, 101));
        setMinimumSize(new java.awt.Dimension(1366, 768));

        jInternalFrame1.setBackground(new java.awt.Color(0, 51, 51));
        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame1.setForeground(java.awt.Color.red);
        jInternalFrame1.setMaximumSize(new java.awt.Dimension(105, 2147483647));
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(105, 29));
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(105, 769));
        jInternalFrame1.setVisible(true);

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\add-user.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\user.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\money.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\discount.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\edit-document.png")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("D:\\Users\\Daniil\\Documents\\NetBeansProjects\\Tooth\\Tooth\\build\\classes\\package1\\images\\logout.png")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jInternalFrame3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrame3.setPreferredSize(new java.awt.Dimension(200, 100));
        jInternalFrame3.setVisible(true);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("Пациент успешно добавлен!");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jInternalFrame7.setTitle("Запись на приём");
        jInternalFrame7.setVisible(true);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите дату" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите врача" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Выберите время" }));

        button1.setLabel("Записать пациента");
        button1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button1ActionPerformed(evt);
            }
        });

        jLabel9.setText("ФИО пациента");

        jLabel11.setText("Акции");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нет" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "нет" }));

        jLabel10.setText("Скидки");

        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane4.setViewportView(textArea1);

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jRadioButton5.setText("Студенты");
        jRadioButton5.setToolTipText("");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jRadioButton6.setText("Пенсионеры");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jRadioButton7.setText("Остальное");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame7Layout.createSequentialGroup()
                                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton7))))
                        .addGap(107, 107, 107))))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame7Layout.createSequentialGroup()
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton7)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jInternalFrame5.setTitle("Акции и скидки");
        jInternalFrame5.setPreferredSize(new java.awt.Dimension(906, 620));
        jInternalFrame5.setVisible(true);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(471, 404));

        jTable1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Код скидки", null, null},
            },
            new String []
            {
                "Код скидки", "Содержание скидки", "Размер скидки"
            }
        )
    );
    jTable1.setPreferredSize(new java.awt.Dimension(225, 500));
    jScrollPane1.setViewportView(jTable1);

    buttonGroup2.add(jRadioButton1);
    jRadioButton1.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
    jRadioButton1.setSelected(true);
    jRadioButton1.setText("Скидки");
    jRadioButton1.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jRadioButton1ActionPerformed(evt);
        }
    });

    buttonGroup2.add(jRadioButton2);
    jRadioButton2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
    jRadioButton2.setText("Акции");
    jRadioButton2.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jRadioButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
    jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
    jInternalFrame5Layout.setHorizontalGroup(
        jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
        .addGroup(jInternalFrame5Layout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addComponent(jRadioButton1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
            .addComponent(jRadioButton2)
            .addGap(241, 241, 241))
    );
    jInternalFrame5Layout.setVerticalGroup(
        jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame5Layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1)
                .addComponent(jRadioButton2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(112, 112, 112))
    );

    jInternalFrame4.setTitle("Услуги");
    jInternalFrame4.setPreferredSize(new java.awt.Dimension(906, 620));
    jInternalFrame4.setVisible(true);

    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
    jRadioButton3.setSelected(true);
    jRadioButton3.setText("Общие");
    jRadioButton3.setToolTipText("");
    jRadioButton3.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jRadioButton3ActionPerformed(evt);
        }
    });

    buttonGroup1.add(jRadioButton4);
    jRadioButton4.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
    jRadioButton4.setText("Продвинутые");
    jRadioButton4.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jRadioButton4ActionPerformed(evt);
        }
    });

    jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jTable2.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {
            {},
            {},
            {},
            {}
        },
        new String []
        {

        }
    ));
    jTable2.setPreferredSize(new java.awt.Dimension(225, 500));
    jScrollPane2.setViewportView(jTable2);

    javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
    jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
    jInternalFrame4Layout.setHorizontalGroup(
        jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame4Layout.createSequentialGroup()
            .addGap(91, 91, 91)
            .addComponent(jRadioButton3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
            .addComponent(jRadioButton4)
            .addGap(256, 256, 256))
        .addGroup(jInternalFrame4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
    );
    jInternalFrame4Layout.setVerticalGroup(
        jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame4Layout.createSequentialGroup()
            .addGap(51, 51, 51)
            .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton4)
                .addComponent(jRadioButton3))
            .addGap(40, 40, 40)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addContainerGap())
    );

    jInternalFrame6.setTitle("Пациенты");
    jInternalFrame6.setVisible(true);

    jLabel8.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
    jLabel8.setText("Введите данные пациента:");

    jButton8.setBackground(new java.awt.Color(0, 153, 153));
    jButton8.setForeground(new java.awt.Color(255, 255, 255));
    jButton8.setText("Поиск пациента");
    jButton8.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jButton8ActionPerformed(evt);
        }
    });

    checkbox1.setLabel("Фамилия");

    checkbox2.setLabel("Имя");

    checkbox3.setLabel("Отчество");

    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][]
        {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String []
        {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jScrollPane3.setViewportView(jTable3);

    jButton9.setBackground(new java.awt.Color(0, 153, 153));
    jButton9.setForeground(new java.awt.Color(255, 255, 255));
    jButton9.setText("Показать всех пациентов");
    jButton9.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jButton9ActionPerformed(evt);
        }
    });

    textField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

    javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
    jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
    jInternalFrame6Layout.setHorizontalGroup(
        jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame6Layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrame6Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(81, 81, 81)
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(117, 117, 117)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE))
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addComponent(jScrollPane3)
                    .addGap(26, 26, 26))))
    );
    jInternalFrame6Layout.setVerticalGroup(
        jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame6Layout.createSequentialGroup()
            .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addGroup(jInternalFrame6Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(checkbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(24, 24, 24)
                    .addGroup(jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jInternalFrame6Layout.createSequentialGroup()
                            .addComponent(checkbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(checkbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(26, 26, 26))
    );

    jInternalFrame2.setBackground(new java.awt.Color(255, 255, 255));
    jInternalFrame2.setResizable(true);
    jInternalFrame2.setTitle("Анкета пациента");
    jInternalFrame2.setPreferredSize(new java.awt.Dimension(500, 700));
    jInternalFrame2.setVisible(true);

    jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

    jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

    jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

    jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

    jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Мужской", "Женский" }));

    jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel1.setText("Фамилия");

    jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel3.setText("Отчество");

    jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel4.setText("Адрес регистрации");

    jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel2.setText("Имя");

    jButton7.setBackground(new java.awt.Color(0, 153, 153));
    jButton7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
    jButton7.setForeground(new java.awt.Color(255, 255, 255));
    jButton7.setText("ДОБАВИТЬ ПАЦИЕНТА");
    jButton7.setPreferredSize(new java.awt.Dimension(240, 30));
    jButton7.addActionListener(new java.awt.event.ActionListener()
    {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            jButton7ActionPerformed(evt);
        }
    });

    jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

    jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel5.setText("Дата рождения");

    jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
    jLabel6.setText("Пол");

    jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

    jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

    javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
    jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
    jInternalFrame2Layout.setHorizontalGroup(
        jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGap(19, 19, 19)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame2Layout.createSequentialGroup()
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jTextField5)))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jInternalFrame2Layout.setVerticalGroup(
        jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jInternalFrame2Layout.createSequentialGroup()
            .addGap(67, 67, 67)
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(28, 28, 28)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(30, 30, 30)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(58, 58, 58))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(31, 31, 31)
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(10, 10, 10))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1449, Short.MAX_VALUE)
            .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(56, 56, 56))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(531, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(507, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(56, 56, 56)))
            .addContainerGap(315, Short.MAX_VALUE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jInternalFrame7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jInternalFrame5, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jInternalFrame6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

        jButton2.setBackground(new Color(0,101,101));
        jButton3.setBackground(new Color(240,240,240));
         jButton5.setBackground(new Color(240,240,240));
        jButton4.setBackground(new Color(240,240,240));
        jButton1.setBackground(new Color(240,240,240));
        ClearFFrame();
        jInternalFrame2.setVisible(true);
        jInternalFrame5.dispose();
        jInternalFrame3.dispose();
        jInternalFrame4.dispose();
        jInternalFrame6.dispose();
        jInternalFrame7.dispose();
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
           jButton5.setBackground(new Color(0,101,101));
        jButton3.setBackground(new Color(240,240,240));
        jButton4.setBackground(new Color(240,240,240));
        jButton1.setBackground(new Color(240,240,240));
        jButton2.setBackground(new Color(240,240,240));
        ClearFFrame();
        jInternalFrame2.dispose();
        jInternalFrame3.dispose();
        jInternalFrame4.dispose();
        jInternalFrame5.dispose();
        jInternalFrame6.dispose();
        jInternalFrame7.setVisible(true);
        if(!patient.equals("")){
            jTextField8.setText(patient);
            jTextField8.setEditable(false);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton6ActionPerformed
    {//GEN-HEADEREND:event_jButton6ActionPerformed
        dispose();
        FirstForm fm = new FirstForm();
        fm.setVisible(true);
        patient = "";
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton7ActionPerformed
    {//GEN-HEADEREND:event_jButton7ActionPerformed
    try
    {
        jLabel7.setText("       Пациент добавлен!");
        String fname = jTextField1.getText();
        String lname = jTextField2.getText();
        String mname = jTextField3.getText();
        String address = jTextField4.getText();
        String birth = jTextField5.getText();
        birth+="-";
        birth+=jTextField7.getText();
        birth+="-";
        birth+=jTextField6.getText();
        String gender = jComboBox1.getSelectedItem().toString();
        if(fname.length()>0 && lname.length()>0 && address.length()>0 && birth.length()==10 && (Integer.parseInt(jTextField5.getText())>1900  && Integer.parseInt(jTextField5.getText())<2020 )){
        Second.add(fname,lname,mname,address,birth,gender);
        if(!patient.equals("0")){
            jInternalFrame2.dispose();
        ClearFFrame();
        jButton2.setBackground(new Color(240,240,240)); 
        patient = fname + " " + lname + " " + mname;
        jInternalFrame3.setVisible(true);
        }else{
            patient = "";
        }
        }else{
            jLabel7.setText("Ошибка добавления пациента!");
            jInternalFrame3.setVisible(true);
        }
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        jRadioButton1.setSelected(true);
        model1 = new DefaultTableModel();
        model1.addColumn("Код скидки");
        model1.addColumn("Содержание скидки");
        model1.addColumn("Размер скидки,%");
    try
    {
        Second.getDiscounts();
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        jTable1.setModel(model1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jInternalFrame2.dispose();
        jInternalFrame3.dispose();
        jInternalFrame4.dispose();
        jInternalFrame7.dispose();
        jInternalFrame6.dispose();
        ClearFFrame();
        jInternalFrame3.dispose();
        jButton2.setBackground(new Color(240,240,240));    
        jButton3.setBackground(new Color(240,240,240));
        jButton4.setBackground(new Color(0,101,101));
        jButton1.setBackground(new Color(240,240,240));
         jButton5.setBackground(new Color(240,240,240));
        jInternalFrame5.setVisible(true);
        jTable1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
    try
    {
        ClearFFrame();
        model3 = new DefaultTableModel();
        model3.addColumn("ID");
        model3.addColumn("Фамилия");
        model3.addColumn("Имя");
        model3.addColumn("Отчество");
        model3.addColumn("Пол");
        model3.addColumn("Дата рождения");
        model3.addColumn("Адрес регистрации");
        FindPatients();
        jTable3.setModel(model3);
        jInternalFrame2.dispose();
        jInternalFrame3.dispose();
        jInternalFrame4.dispose();
        jInternalFrame5.dispose();
        jInternalFrame7.dispose();
        ClearFFrame();
        jButton1.setBackground(new Color(0,101,101));
        jButton3.setBackground(new Color(240,240,240));
        jButton2.setBackground(new Color(240,240,240));
        jButton4.setBackground(new Color(240,240,240));
         jButton5.setBackground(new Color(240,240,240));
        jInternalFrame6.setVisible(true);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        jRadioButton3.setSelected(true);
        model2 = new DefaultTableModel();
        model2.addColumn("Код услуги");
        model2.addColumn("Название услуги");
        model2.addColumn("Цена");
    try
    {
        getObj();
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        jTable2.setModel(model2);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        jInternalFrame2.dispose();
       jInternalFrame3.dispose();
       jInternalFrame5.dispose();
       jInternalFrame6.dispose();
       jInternalFrame7.dispose();
        ClearFFrame();
        jButton2.setBackground(new Color(240,240,240));
       jButton4.setBackground(new Color(240,240,240));
       jButton1.setBackground(new Color(240,240,240));
        jButton5.setBackground(new Color(240,240,240));
       jButton3.setBackground(new Color(0,101,101));
       jInternalFrame4.setVisible(true);
       jTable2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton1ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton1ActionPerformed
    try
    {
        model1 = new DefaultTableModel();
        model1.addColumn("Код скидки");
        model1.addColumn("Содержание скидки");
        model1.addColumn("Размер скидки,%");
        Second.getDiscounts();
        jTable1.setModel(model1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton2ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton2ActionPerformed
           try
    {
        model1 = new DefaultTableModel();
        model1.addColumn("Код акции");
        model1.addColumn("Содержание акции");
        model1.addColumn("Дата начала");
        model1.addColumn("Дата окончания");
        model1.addColumn("Бонусы");
        Second.getActions();
        jTable1.setModel(model1);
         jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(500);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(450);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton3ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton3ActionPerformed
    try
    {
        model2 = new DefaultTableModel();
        model2.addColumn("Код услуги");
        model2.addColumn("Название услуги");
        model2.addColumn("Цена");
        getObj();
        jTable2.setModel(model2);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton4ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton4ActionPerformed
    try
    {
        model2 = new DefaultTableModel();
        model2.addColumn("Код услуги");
        model2.addColumn("Название услуги");
        model2.addColumn("Цена");
        getAdv();
        jTable2.setModel(model2);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(1000);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton8ActionPerformed
    {//GEN-HEADEREND:event_jButton8ActionPerformed
    try
    {
        String str = textField1.getText();
        FindPatients(str);
        textField1.setText("");
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton9ActionPerformed
    {//GEN-HEADEREND:event_jButton9ActionPerformed
    try
    {
        model3 = new DefaultTableModel();
        model3.addColumn("ID");
        model3.addColumn("Фамилия");
        model3.addColumn("Имя");
        model3.addColumn("Отчество");
        model3.addColumn("Пол");
        model3.addColumn("Дата рождения");
        model3.addColumn("Адрес регистрации");
        FindPatients();
        jTable3.setModel(model3);
        textField1.setText("");
        checkbox1.setState(false);
        checkbox2.setState(false);
        checkbox3.setState(false);
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jComboBox3ItemStateChanged
    {//GEN-HEADEREND:event_jComboBox3ItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED) {
             jComboBox2.removeAllItems();
       jComboBox2.addItem("Выберите дату");
          Object item = evt.getItem();
          if(!item.equals("Выберите врача")){
              try {
                   ArrayList<String> item1 = new ArrayList<String>();
                  try
                  {
                      getSchedule(item1,jComboBox3.getSelectedItem().toString());
                  }
                  catch (ParseException ex)
                  {
                      Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
                  }
                   Object[] arr1 = item1.toArray();
                   int c =0;
         for(int i=0;i<item1.size();i++){
             for(int j=i+1;j<arr1.length;j++){
                 if(arr1[i].equals(arr1[j])){
                    c=1;
                     break; 
                 }
             }
                 if(c==0){
                      jComboBox2.addItem(arr1[i].toString());
                 }else{
                     c=0;
                 }
             
        }
              }
              catch (ClassNotFoundException ex) {
                  Logger.getLogger(ForthForm.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jComboBox2ItemStateChanged
    {//GEN-HEADEREND:event_jComboBox2ItemStateChanged
       
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            jComboBox4.removeAllItems();
       jComboBox4.addItem("Выберите время");
          Object item = evt.getItem();
          if(!item.equals("Выберите дату")){
              try {
                   ArrayList<String> item2 = new ArrayList<String>();
                  try
                  {
                      getSchedule(item2,jComboBox3.getSelectedItem().toString(),jComboBox2.getSelectedItem().toString());
                       ArrayList<String> act = new ArrayList<String>();
                       try
                       {
                           Second.getActions(act,jComboBox2.getSelectedItem().toString());
                       }
                       catch (SQLException ex)
                       {
                           Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
                       }
                    Object[] act1 = act.toArray();
                    jComboBox6.removeAllItems();
                    jComboBox6.addItem("нет");
                    for(int i=0;i<act.size();i++){
            jComboBox6.addItem(act1[i].toString());
        }
                  }
                  catch (ParseException ex)
                  {
                      Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
                  }
                   Object[] arr2 = item2.toArray();
         for(int i=0;i<item2.size();i++){
            jComboBox4.addItem(arr2[i].toString());
        }
              }
              catch (ClassNotFoundException ex) {
                  Logger.getLogger(ForthForm.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void button1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button1ActionPerformed
    {//GEN-HEADEREND:event_button1ActionPerformed
        jLabel7.setText("Запись прошла успешно!");      
        String doctor = jComboBox3.getSelectedItem().toString();
       String  date = jComboBox2.getSelectedItem().toString();
       String time = jComboBox4.getSelectedItem().toString();
       String FIO = jTextField8.getText();
       String comm = textArea1.getText();
       String dis = jComboBox5.getSelectedItem().toString();
       String ac = jComboBox6.getSelectedItem().toString();
       if((!FIO.equals("")) && (!doctor.equals("Выберите врача")) && (!time.equals("Выберите время")) && (!date.equals("Выберите дату")) ){
            try 
            {
                wr(doctor,date,time,FIO,dis,ac,comm);
                rr(doctor,date,time);
                jLabel7.setVisible(true);
                jInternalFrame3.setVisible(true);
                clean();
                patient = "";
                jTextField8.setEditable(true);
            }
            catch (ClassNotFoundException ex)
            {
                Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ParseException ex)
            {
                Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(Exception ex){
                Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
            }
       }else{
           jLabel7.setText("Ошибка записи");
           jLabel7.setVisible(true);
           jInternalFrame3.setVisible(true);
           jInternalFrame7.toBack();
           jInternalFrame3.toFront();
           clean();
       }
    }//GEN-LAST:event_button1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton5ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton5ActionPerformed
    try
    {
        jComboBox5.removeAllItems();
        jComboBox5.addItem("нет");
        ArrayList<String> disc = new ArrayList<String>();
        Second.getDiscounts(disc, "students");
        Object[] di = disc.toArray();
         for(int i=0;i<disc.size();i++){
            jComboBox5.addItem(di[i].toString());
        }
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton6ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton6ActionPerformed
    try
    {
        jComboBox5.removeAllItems();
        jComboBox5.addItem("нет");
        ArrayList<String> disc = new ArrayList<String>();
        Second.getDiscounts(disc, "old");
        Object[] di = disc.toArray();
        for(int i=0;i<disc.size();i++){
            jComboBox5.addItem(di[i].toString());
        }
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButton7ActionPerformed
    {//GEN-HEADEREND:event_jRadioButton7ActionPerformed
    try
    {
        jComboBox5.removeAllItems();
        jComboBox5.addItem("нет");
        ArrayList<String> disc = new ArrayList<String>();
        Second.getDiscounts(disc, "other");
        Object[] di = disc.toArray();
        for(int i=0;i<disc.size();i++){
            jComboBox5.addItem(di[i].toString());
        }
    }
    catch (ClassNotFoundException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (SQLException ex)
    {
        Logger.getLogger(SecondForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SecondForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SecondForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SecondForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SecondForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                sc.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static java.awt.Button button1;
    public static javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.ButtonGroup buttonGroup3;
    public static java.awt.Checkbox checkbox1;
    public static java.awt.Checkbox checkbox2;
    public static java.awt.Checkbox checkbox3;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JButton jButton4;
    public static javax.swing.JButton jButton5;
    public static javax.swing.JButton jButton6;
    public static javax.swing.JButton jButton7;
    public static javax.swing.JButton jButton8;
    public static javax.swing.JButton jButton9;
    public static javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    public static javax.swing.JComboBox<String> jComboBox3;
    public static javax.swing.JComboBox<String> jComboBox4;
    public static javax.swing.JComboBox<String> jComboBox5;
    public static javax.swing.JComboBox<String> jComboBox6;
    public static javax.swing.JInternalFrame jInternalFrame1;
    public static javax.swing.JInternalFrame jInternalFrame2;
    public static javax.swing.JInternalFrame jInternalFrame3;
    public static javax.swing.JInternalFrame jInternalFrame4;
    public static javax.swing.JInternalFrame jInternalFrame5;
    public static javax.swing.JInternalFrame jInternalFrame6;
    public static javax.swing.JInternalFrame jInternalFrame7;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JRadioButton jRadioButton3;
    public static javax.swing.JRadioButton jRadioButton4;
    public static javax.swing.JRadioButton jRadioButton5;
    public static javax.swing.JRadioButton jRadioButton6;
    public static javax.swing.JRadioButton jRadioButton7;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable3;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    public static javax.swing.JTextField jTextField5;
    public static javax.swing.JTextField jTextField6;
    public static javax.swing.JTextField jTextField7;
    public static javax.swing.JTextField jTextField8;
    public static javax.swing.JTextArea textArea1;
    public static javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
}
